### ISSUE TITLE
actors can violate collision if moving through a boundary "sideways"

### ISSUE THREAD

**Issue by Pomax** [Pomax/Pjs-2D-Game-Engine#8]
this is most obvious when jumping through a corner where two boundaries meet. There are multiple trajectories possible where the actor ends up going through each boundary in a permitted way, even though the combination of the two boundaries should result in a block:

```
↘
 　┌--
```

**Comment by epje** [comment]
Did you find a fix for this in the end?

**Comment by Pomax** [comment]
no idea, it's been so long that I remember nothing of this codebase, unfortunately.
